service: default

runtime: go119
instance_class: F1

handlers:
- url: /.*
  script: auto
  secure: always

env_variables:
  # Required for Google Cloud APIs
  PROJECT_ID: 'partner-ecosystem-exchange'
  LOCATION_ID: 'europe-west3'
  SERVICE_NAME: 'default'
  # content
  CONTENT_ROOT: '_site'
  